export const PRIMARYDESCRIPTIONCOL = "PRIMARYDESCRIPTIONCOL";
export const PRIMARYIMAGECOL = "PRIMARYIMAGECOL";
export const ADDITIONALDESCRIPTIONCOL = "ADDITIONALDESCRIPTIONCOL";
export const ADDITIONALIMAGECOL = "ADDITIONALIMAGECOL";
export const USERCOL = "USERCOL";
export const USERIMAGECOL = "USERIMAGECOL";
export const QUESTIONIDCOL = "QUESTIONIDCOL";
export const ANSWERIDCOL = "ANSWERIDCOL";
export const ISCORRECTCOL = "ISCORRECTCOL";
export const RATINGCOL = "RATINGCOL";
export const LIKECOL = "QUESTIONSLIST";
export const QUESTIONSLIST = "QUESTIONSLIST";
export const ANSWERSLIST = "ANSWERSLIST";
export const RATINGSLIST = "RATINGSLIST";
export const LIKESLIST = "LIKESLIST";

//PRIMARYDESCRIPTIONCOL, PRIMARYIMAGECOL,ADDITIONALDESCRIPTIONCOL,ADDITIONALIMAGECOL,USERCOL,USERIMAGECOL,QUESTIONIDCOL,ANSWERIDCOL,ISCORRECTCOL,RATINGCOL,LIKECOL
//PrimaryDescriptionCol, PrimaryImageCol, AdditionalDescriptionCol,AdditionalImageCol,UserCol,UserImageCol,QuestionIdCol,AnswerIdCol,IsCorrectCol,RatingCol,Like
